#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

### directory to check
DIR=$1

### Check if directory exist
if ! [ -d "$DIR" ]; then
  printf "Directory: \033[1m$DIR\033[0m not exist\n" >&2
  exit 1
fi
