#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Description: Clone all GitHub Repositories
# Usage: clall [GITHUB_ACCESS_TOKEN]
# Example: clall ghp_000000000000000000000000000000000000

### Args
TOKEN=${1:-}

# Check arguments
if [ -z "$TOKEN" ]; then
  printf "\033[1mclall\033[0m: Clone all GitHub Repositories\n" >&2
  printf "Usage: \033[1mclall\033[0m [GITHUB_ACCESS_TOKEN]\n" >&2
  printf "       \033[1mclall\033[0m ghp_000000000000000000000000000000000000\n" >&2
  exit 1
fi

# Check commands
command -v curl &>/dev/null || {
  echo "curl is not installed" >&2
  exit 1
}
command -v jq &>/dev/null || {
  echo "jq is not installed" >&2
  exit 1
}
command -v git &>/dev/null || {
  echo "git is not installed" >&2
  exit 1
}

REPO_LIST=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" -s "https://api.github.com/user/repos?type=owner&per_page=100" | jq .[].ssh_url | sed -e 's/^"//' -e 's/"$//')
mapfile -t REPOS <<<"$REPO_LIST"
REPO_LIST_LEN=${#REPOS[@]}
TMPDIR="$(mktemp -d -t "$(basename $0)")"
for REPO in "${REPOS[@]}"; do
  REPO_NAME="$(basename "$REPO" .git)"
  (
    if git clone --quiet "$REPO"; then
      touch "$TMPDIR/$REPO_NAME"
      FINISHED=$(ls -1 "$TMPDIR" | wc -l | tr -d ' ')
      printf "Clone [%s/%s] \033[1m%s\033[0m ok\n" "$FINISHED" "$REPO_LIST_LEN" "$REPO_NAME"
    fi
  ) &
done
wait
rm -rf "$TMPDIR"
