#! /usr/bin/env bash
set -o errexit
set -o pipefail

### cmd
CMD=$(basename "$0")
### Description
DESC="Clone all GitHub REPOsitories"
### Usage
USAGE="[GITHUB_ACCESS_TOKEN]"
### Example
EXAMPLE="ghp_000000000000000000000000000000000000"

### Args
TOKEN=$1

### Check args exist
chkarg "$TOKEN" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"

### Check cmd exist
chkcmd "curl"
chkcmd "jq"
chkcmd "git"

REPO_LIST=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" -s "https://api.github.com/user/repos?type=owner&per_page=100" | jq .[].ssh_url | sed -e 's/^"//' -e 's/"$//')
REPO_LIST_LEN=$(expr $(wc -w <<<"$REPO_LIST"))
TMPFILE="$(mktemp -t "$(basename $0)")"
FINISHED=1
echo "0" >"$TMPFILE"
for REPO in $REPO_LIST; do
  REPO_NAME="$(basename "$REPO" .git)"
  git clone --quiet "$REPO" && FINISHED_NEW=$(expr $(cat "$TMPFILE") + 1) && echo "$FINISHED_NEW" >"$TMPFILE" && printf "Clone [%s/%s] \033[1m%s\033[0m ok\n" "$(cat "$TMPFILE")" "$REPO_LIST_LEN" "$REPO_NAME" &
done
wait
rm -f "$TMPFILE"
