#! /usr/bin/env bash
set -o errexit
set -o pipefail

### Check cmd exist
chkcmd "git"
chkcmd "npm"
chkcmd "npx"

### Check is node project exist
chkfile package.json
chkfile package-lock.json

### Sync project
git pull --quiet

### Check version
COMMIT_MSG_BODY="$(npx -y npm-check-updates@latest -p npm -t semver --install never | sed "1,2d; $d" | sed "$ d")"

printf "\n$COMMIT_MSG_BODY\n\n"

if ! [ "$COMMIT_MSG_BODY" = "" ]; then
  ### Upgrade packages
  npx -y npm-check-updates@latest -p npm -t semver --install never --loglevel silent -u

  ### Sync lockfile
  rm -rf node_modules
  rm -f package-lock.json
  npm i

  ### Add to git
  git add package-lock.json
  git add package.json
  git commit -m "fix(deps): update all non-major dependencies" -m "$COMMIT_MSG_BODY" -m "by depsup script"
  git push

  ### Check version again
  npx -y npm-check-updates@latest -p npm -t latest --install never
else
  ### Sync node_modules
  npm ci
fi
