#! /usr/bin/env bash
set -o errexit
set -o pipefail

chkcmd "git"

### Backup mkbopomofo config

CONFIG_HOME="$(dirname "$(dirname $0)")/configs"
CONFIG_DIR="mcbopomofo"
cd "$CONFIG_HOME" || exit
git add "$CONFIG_DIR"
echo ""
printf "Backup $CONFIG_DIR config..."
git commit -q -m "feat: Update $CONFIG_DIR config by mbk"
git push -q
echo "done."
echo ""
