#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Description: Multi-dig-ipv6: Check AAAA records on different DNS server at once.
# Usage: mdig6 [domain]
# Example: mdig6 'is1-ssl.mzstatic.com'


### Args
DOMAIN=${1:-}

# Check arguments
if [ -z "$DOMAIN" ]; then
  printf "\033[1mmdig6\033[0m: Multi-dig-ipv6: Check AAAA records on different DNS server at once.\n" >&2
  printf "Usage: \033[1mmdig6\033[0m [domain]\n" >&2
  printf "       \033[1mmdig6\033[0m 'is1-ssl.mzstatic.com'\n" >&2
  exit 1
fi

# Check commands
command -v dig &> /dev/null || { echo "dig is not installed" >&2; exit 1; }

DNS_SERVERS=("Google|8.8.8.8" "Cloudflare|1.1.1.1" "Hinet|168.95.192.1" "Hinet|168.95.1.1" "System|127.0.0.1")

for SERVER in "${DNS_SERVERS[@]}"; do
  IFS='|' read -ra ADDR <<<"$SERVER"
  SERVER_NAME=${ADDR[0]}
  SERVER_IP=${ADDR[1]}
  if [ "$SERVER_NAME" = "System" ]; then
    printf "\033[1mSystem\033[0m\n"
    dig "$DOMAIN" +noall +answer +stats AAAA | awk '/IN[ \t]+AAAA/ {print $NF} /Query time/ {print "time: "$4, "ms"}'
    echo ""
  else
    printf "\033[1m%s\033[0m %s\n" "$SERVER_NAME" "$SERVER_IP"
    dig "@$SERVER_IP" "$DOMAIN" +noall +answer +stats AAAA | awk '/IN[ \t]+AAAA/ {print $NF} /Query time/ {print "time: "$4, "ms"}'
    echo ""
  fi
done
