#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Description: Clip Maker
# Usage: mkclp [input_file] [from(hh:mm:ss or sec)] [during(sec)]
# Example: mkclp 'input.mp4' 01:02:08 11.0

### Args
INPUT_FILE=${1:-}
START=${2:-}
DURATION=${3:-}

# Check arguments
if [[ -z "$DURATION" ]]; then
  printf "\033[1mmkclp\033[0m: Clip Maker\n" >&2
  printf "Usage: \033[1mmkclp\033[0m [input_file] [from(hh:mm:ss or sec)] [during(sec)]\n" >&2
  printf "       \033[1mmkclp\033[0m 'input.mp4' 01:02:08 11.0\n" >&2
  exit 1
fi

# Check commands
command -v ffmpeg &>/dev/null || {
  echo "ffmpeg is not installed" >&2
  exit 1
}
command -v ffprobe &>/dev/null || {
  echo "ffprobe is not installed" >&2
  exit 1
}

# Check files
[[ -f "$INPUT_FILE" ]] || {
  echo "File $INPUT_FILE not exist" >&2
  exit 1
}

# Detect container format and video codec
FORMAT=$(ffprobe -v error -show_entries format=format_name -of default=noprint_wrappers=1:nokey=1 "$INPUT_FILE" || true)
VIDEO_CODEC=$(ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 "$INPUT_FILE" || true)

VC_ARGS=(-c:v copy)
# If container format is not mp4, or video codec is not h264/hevc, re-encode with hevc_videotoolbox
if [[ ! "$FORMAT" =~ "mp4" ]] || [[ "$VIDEO_CODEC" != "h264" && "$VIDEO_CODEC" != "hevc" ]]; then
  VC_ARGS=(-c:v hevc_videotoolbox -q:v 45 -tag:v hvc1)
fi

### Output file
OUTPUT_FILE="$(date +"%Y%m%d%H%M%S")_clip.mp4"

ffmpeg -y -hide_banner \
  -loglevel error \
  -ss "$START" \
  -i "$INPUT_FILE" \
  -t "$DURATION" \
  -map 0:v:0 \
  -map 0:a:0? \
  "${VC_ARGS[@]}" \
  -c:a aac \
  -map_chapters -1 \
  -movflags +faststart \
  "$OUTPUT_FILE"

printf "%s " "$OUTPUT_FILE"
ls -lh "$OUTPUT_FILE" | awk -F " " {'print $5'}
