#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Description: Gif Maker (24fps, 480p, q100)
# Usage: mkgifv [input_file] [from(hh:mm:ss or sec)] [during(sec)]
# Example: mkgifv 'input.mp4' 01:02:08 11.0

### Args
INPUT_FILE=${1:-}
START=${2:-}
DURATION=${3:-}

# Check arguments
if [ -z "$DURATION" ]; then
  printf "\033[1mmkgifv\033[0m: Gif Maker (24fps, 480p, q100)\n" >&2
  printf "Usage: \033[1mmkgifv\033[0m [input_file] [from(hh:mm:ss or sec)] [during(sec)]\n" >&2
  printf "       \033[1mmkgifv\033[0m 'input.mp4' 01:02:08 11.0\n" >&2
  exit 1
fi

# Check commands
command -v ffmpeg &>/dev/null || {
  echo "ffmpeg is not installed" >&2
  exit 1
}
command -v gifski &>/dev/null || {
  echo "gifski is not installed" >&2
  exit 1
}

# Check files
[ -f "$INPUT_FILE" ] || {
  echo "File $INPUT_FILE not exist" >&2
  exit 1
}

### quality
QUALITY=85
### fps
FPS=24
### width
WIDTH=480
### Output file
OUTPUT_FILE="$(date +"%Y%m%d%H%M%S")_v.gif"

ffmpeg -hide_banner \
  -loglevel error \
  -ss "$START" \
  -t "$DURATION" \
  -i "$INPUT_FILE" \
  -vf "fps=$FPS,scale=$WIDTH:-1:flags=lanczos" \
  -f yuv4mpegpipe - |
  gifski -q \
    -Q "$QUALITY" \
    -o "$OUTPUT_FILE" -

printf "%s " "$OUTPUT_FILE"
ls -lh "$OUTPUT_FILE" | awk -F " " {'print $5'}
