#! /usr/bin/env bash
set -o errexit
set -o pipefail

### cmd
CMD=$(basename "$0")
### Description
DESC="Re-Encoder: re-encode a mp4"
### Usage
USAGE="[input_file]"
### Example
EXAMPLE="'input.mp4'"

### Args
INPUT_FILE=$1

### Check args exist
chkarg "$INPUT_FILE" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"

### Check cmd exist
chkcmd "ffmpeg"

### Check file exist
chkfile "$INPUT_FILE"

### Temp File
TMPFILE="$(mktemp -t "$(basename $0)").mp4"

ffmpeg -y \
  -hide_banner \
  -loglevel error \
  -i "$INPUT_FILE" \
  -map 0:v:0 \
  -map 0:a \
  -map 0:s? \
  -c copy \
  -c:s mov_text \
  -movflags +faststart \
  -f mp4 \
  "$TMPFILE"

mv "$TMPFILE" "$INPUT_FILE"
