#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Description: Re-Encoder: re-encode a mp4
# Usage: rec [input_file]
# Example: rec 'input.mp4'


### Args
INPUT_FILE=${1:-}

# Check arguments
if [ -z "$INPUT_FILE" ]; then
  printf "\033[1mrec\033[0m: Re-Encoder: re-encode a mp4\n" >&2
  printf "Usage: \033[1mrec\033[0m [input_file]\n" >&2
  printf "       \033[1mrec\033[0m 'input.mp4'\n" >&2
  exit 1
fi

# Check commands
command -v ffmpeg &> /dev/null || { echo "ffmpeg is not installed" >&2; exit 1; }

# Check files
[ -f "$INPUT_FILE" ] || { echo "File $INPUT_FILE not exist" >&2; exit 1; }

### Temp File
TMPFILE="$(mktemp -t "$(basename $0)").mp4"

ffmpeg -y \
  -hide_banner \
  -loglevel error \
  -i "$INPUT_FILE" \
  -map 0:v:0 \
  -map 0:a \
  -map 0:s? \
  -c copy \
  -c:s mov_text \
  -movflags +faststart \
  -f mp4 \
  "$TMPFILE"

mv "$TMPFILE" "$INPUT_FILE"
