#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Description: Reset macOS Launchpad layout and restart Dock
# Usage: rsl
# Example: rsl

rm -rf /private$(getconf DARWIN_USER_DIR)com.apple.dock.launchpad

killall Dock
