#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Description: Check for Node.js package updates in the current directory
# Usage: up
# Example: up

# Check commands
command -v npm &>/dev/null || {
    echo "npm is not installed" >&2
    exit 1
}
command -v npx &>/dev/null || {
    echo "npx is not installed" >&2
    exit 1
}

### Check is node project exist
[[ -f "package.json" ]] || {
    echo "File package.json not exist" >&2
    exit 1
}

### Check package to update
npx -y npm-check-updates@latest -p npm -t latest --install never
