#! /usr/bin/env bash
set -o errexit
set -o pipefail

### Check cmd exist
chkcmd "git"
chkcmd "pnpm"

### Check is node project exist
chkfile package.json
chkfile pnpm-lock.yaml

### Sync project
git pull --quiet

### Check version
PACKEGES_TO_UPDATE_MSG="$(pnpm dlx npm-check-updates@latest -p pnpm -t minor --install never | sed "1,2d; $d" | sed "$ d")"
PACKEGES_TO_UPDATE="$(pnpm dlx npm-check-updates@latest -p pnpm -t minor --install never --jsonUpgraded | jq -cr 'to_entries | map("\(.key)@\(.value|tostring)") | .[]')"

readarray -t <<<$PACKEGES_TO_UPDATE_MSG
if ! [ "$PACKEGES_TO_UPDATE" = "" ]; then
  ### If any packages need update, one updated package per commit/push(for ci)
  rm -rf node_modules
  rm -f pnpm-lock.yaml
  IDX=0
  for PACKAGE in $PACKEGES_TO_UPDATE; do
    echo " ${MAPFILE[$IDX]}"
    pnpm i "$PACKAGE" --lockfile-only --reporter=silent
    git add pnpm-lock.yaml
    git add package.json
    git commit -q -m "chore(deps): update dependency ${MAPFILE[$IDX]}"
    git push -q
    IDX=$(expr $IDX + 1)
  done
else
  ### If no package needs update, sync lockfile
  rm -rf node_modules
  rm -f pnpm-lock.yaml
  pnpm i --lockfile-only --reporter=silent

  ### If lockfile updated, add to git
  if [ "$(git status --short)" != "" ]; then
    git add pnpm-lock.yaml
    git commit -q -m "chore(deps): Update dependencies that are not directly dependent"
    git push -q
  fi
fi

### Check version again
pnpm dlx npm-check-updates@latest -p pnpm -t latest --install never
### install packages
pnpm i --reporter=silent
