#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Check commands
command -v git &>/dev/null || {
  echo "git is not installed" >&2
  exit 1
}
command -v npm &>/dev/null || {
  echo "npm is not installed" >&2
  exit 1
}
command -v npx &>/dev/null || {
  echo "npx is not installed" >&2
  exit 1
}

### Check is node project exist
[ -f "package.json" ] || {
  echo "File package.json not exist" >&2
  exit 1
}
[ -f "package-lock.json" ] || {
  echo "File package-lock.json not exist" >&2
  exit 1
}

### Sync project
git pull --quiet

### Check version
PACKEGES_TO_UPDATE_MSG="$(npx -y npm-check-updates@latest -p npm -t minor --install never | sed "1,2d; $d" | sed "$ d")"
PACKEGES_TO_UPDATE="$(npx -y npm-check-updates@latest -p npm -t minor --install never --jsonUpgraded | jq -cr 'to_entries | map("\(.key)@\(.value|tostring)") | .[]')"

readarray -t <<<$PACKEGES_TO_UPDATE_MSG
if ! [ "$PACKEGES_TO_UPDATE" = "" ]; then
  ### If any packages need update, one updated package per commit/push(for ci)
  rm -rf node_modules
  rm -f package-lock.json
  IDX=0
  for PACKAGE in $PACKEGES_TO_UPDATE; do
    echo " ${MAPFILE[$IDX]}"
    npm install "$PACKAGE" --package-lock-only --ignore-scripts --loglevel silent
    git add package-lock.json
    git add package.json
    git commit -q -m "chore(deps): update dependency ${MAPFILE[$IDX]}"
    git push -q
    IDX=$((IDX + 1))
  done
else
  ### If no package needs update, sync lockfile
  rm -rf node_modules
  rm -f package-lock.json
  npm install --package-lock-only --ignore-scripts --loglevel silent

  ### If lockfile updated, add to git
  if [ "$(git status --short)" != "" ]; then
    git add package-lock.json
    git commit -q -m "chore(deps): Update dependencies that are not directly dependent"
    git push -q
  fi
fi

### Check version again
npx -y npm-check-updates@latest -p npm -t latest --install never
### install packages
npm ci
