#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

### Check if git installed
if ! [ -x "$(command -v git)" ]; then
  echo "git is not installed" >&2
  exit 1
fi

RULE_DIR="$(dirname "$(dirname $0)")/rules"
git add "$RULE_DIR/ubo-desktop.txt"
git add "$RULE_DIR/ubo-mobile.txt"
git add "$RULE_DIR/ubo-font.txt"
git commit -qm "feat: update ubo-rules by urb"
git push -q
