#! /usr/bin/env bash
set -o errexit
set -o pipefail

chkcmd "git"

RULE_DIR="$(dirname "$(dirname $0)")/rules"
cd "$RULE_DIR"
cd ..
git add "$RULE_DIR/ubo-desktop.txt"
git add "$RULE_DIR/ubo-mobile.txt"
git add "$RULE_DIR/ubo-font.txt"
git commit -qm "feat: update ubo-rules by urb"
git push -q
