#! /usr/bin/env bash
set -o errexit
set -o pipefail

### cmd
CMD=$(basename "$0")
### Description
DESC="Youtube Music Album Downloader"
### Usage
USAGE="[playlist_url]"
### Example
EXAMPLE="'https://music.youtube.com/playlist?list=OLAK5uy_mkYbYGnRqE3zD-9Cy3lA8C5oE7FzEbarg'"

### Args
URL=$1

### Check args exist
chkarg "$URL" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"

### Check cmd exist
chkcmd "yt-dlp"

RAW_ALBUM_TITLE=$(yt-dlp \
  --no-warnings \
  --flat-playlist \
  --playlist-end 1 \
  --print "%(playlist_title)s" \
  --cookies-from-browser chrome \
  "$URL")

DL_DIR="ytalb_$(date +"%Y%m%d%H%M%S")"

DISPLAY_ALBUM_TITLE="${RAW_ALBUM_TITLE/Album - /""}"

printf "Download \033[1m$DISPLAY_ALBUM_TITLE\033[0m\nTo directory: \033[1m$DL_DIR\033[0m\n"

mkdir "$DL_DIR"
cd "$DL_DIR"

yt-dlp \
  --no-warnings \
  --progress \
  -f bestaudio \
  --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" \
  --extract-audio \
  --embed-thumbnail \
  --embed-metadata \
  --parse-metadata 'playlist_index:%(meta_track)s' \
  --convert-thumbnails jpg \
  --print before_dl:"[%(playlist_index)s/%(playlist_count)s]: %(playlist_index)s %(title)s" \
  -o "%(playlist_index)s %(title)s.%(ext)s" \
  --cookies-from-browser chrome \
  "$URL"
