#! /usr/bin/env bash
set -o errexit
set -o pipefail

### cmd
CMD=$(basename "$0")
### Description
DESC="Youtube Music Album Downloader"
### Usage
USAGE="[playlist_url]"
### Example
EXAMPLE="'https://music.youtube.com/playlist?list=OLAK5uy_mkYbYGnRqE3zD-9Cy3lA8C5oE7FzEbarg'"

### Args
URL=$1

### Check args exist
chkarg "$URL" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"

### Check cmd exist
chkcmd "yt-dlp"

RAW_ALBUM_TITLE=$(yt-dlp \
  --no-warnings \
  --playlist-items 1 \
  --print "%(album|playlist_title)s" \
  --cookies-from-browser edge \
  "$URL")

DISPLAY_ALBUM_TITLE=$(echo "$RAW_ALBUM_TITLE" | sed -E 's/^(Album|EP|Single) - //')

DL_DIR="ytalb_$(date +"%Y%m%d%H%M%S")"

printf "Downloading: \033[36m%s\033[0m\n" "$DISPLAY_ALBUM_TITLE"
printf "To directory: \033[33m%s\033[0m\n\n" "$DL_DIR"

yt-dlp \
  --no-warnings \
  --progress \
  -f "141/140/bestaudio[ext=m4a]" \
  --extract-audio \
  --audio-format m4a \
  --embed-thumbnail \
  --convert-thumbnails jpg \
  --ppa "ThumbnailsConvertor+FFmpeg_o:-vf crop=ih:ih" \
  --embed-metadata \
  --parse-metadata 'playlist_index:%(meta_track)s' \
  --print before_dl:"[%(playlist_index)02d/%(playlist_count)02d] %(title)s" \
  -o "$DL_DIR/%(playlist_index)02d - %(title)s.%(ext)s" \
  --cookies-from-browser edge \
  "$URL"
