#! /usr/bin/env bash
set -o errexit
set -o pipefail

### cmd
CMD=$(basename "$0")
### Description
DESC="Youtube Video Cliper"
### Usage
USAGE="[video_link] [from(hh:mm:ss or sec)] [during(sec)]"
### Example
EXAMPLE="'https://www.youtube.com/watch?v=JoSY6AWKqHs' 00:01:59 2"

### Args
URL=$1
START=$2
DURATION=$3

### Check args exist
chkarg "$URL" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"
chkarg "$START" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"
chkarg "$DURATION" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"

### Check cmd exist
chkcmd "yt-dlp"
chkcmd "ffmpeg"

### Temp File
TMPFILE="$(mktemp -t "$(basename $0)")"
### Output file
OUTPUT_FILE="$(date +"%Y%m%d%H%M%S").mp4"

STREAM_URL=$(yt-dlp -g -S "vcodec:h264,acodec:m4a" "$URL" 2>/dev/null)

ffmpeg -y \
  -hide_banner \
  -loglevel error \
  -ss "$START" \
  -i "$STREAM_URL" \
  -t "$DURATION" \
  -map 0:v:0 \
  -map 0:a:0 \
  -c:v hevc_videotoolbox \
  -q:v 45 \
  -c:a aac \
  -map_chapters -1 \
  -movflags +faststart \
  -f mp4 \
  -tag:v hvc1 \
  "$TMPFILE"

cp "$TMPFILE" "$OUTPUT_FILE"

printf "%s " "$OUTPUT_FILE"
ls -lh "$OUTPUT_FILE" | awk -F " " {'print $5'}
