#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Description: Youtube Video Cliper
# Usage: ytclp [video_id] [from(hh:mm:ss or sec)] [during(sec)]
# Example: ytclp JoSY6AWKqHs 00:01:59 2


### Args
URL=${1:-}
START=${2:-}
DURATION=${3:-}

# Check arguments
if [ -z "$DURATION" ]; then
  printf "\033[1mytclp\033[0m: Youtube Video Cliper\n" >&2
  printf "Usage: \033[1mytclp\033[0m [video_id] [from(hh:mm:ss or sec)] [during(sec)]\n" >&2
  printf "       \033[1mytclp\033[0m JoSY6AWKqHs 00:01:59 2\n" >&2
  exit 1
fi

# Check commands
command -v yt-dlp &> /dev/null || { echo "yt-dlp is not installed" >&2; exit 1; }
command -v ffmpeg &> /dev/null || { echo "ffmpeg is not installed" >&2; exit 1; }

### Temp File
TMPFILE="$(mktemp -t "$(basename $0)")"
### Output file
OUTPUT_FILE="$(date +"%Y%m%d%H%M%S").mp4"

STREAM_URL=$(yt-dlp -g -S "vcodec:h264,acodec:m4a" "$URL" 2>/dev/null)

ffmpeg -y \
  -hide_banner \
  -loglevel error \
  -ss "$START" \
  -i "$STREAM_URL" \
  -t "$DURATION" \
  -map 0:v:0 \
  -map 0:a:0 \
  -c:v hevc_videotoolbox \
  -q:v 45 \
  -c:a aac \
  -map_chapters -1 \
  -movflags +faststart \
  -f mp4 \
  -tag:v hvc1 \
  "$TMPFILE"

cp "$TMPFILE" "$OUTPUT_FILE"

printf "%s " "$OUTPUT_FILE"
ls -lh "$OUTPUT_FILE" | awk -F " " {'print $5'}
