#! /usr/bin/env bash
set -o errexit
set -o pipefail

### cmd
CMD=$(basename "$0")
### Description
DESC="Youtube Gif Maker (12fps)"
### Usage
USAGE="[video_link] [from(hh:mm:ss or sec)] [during(sec)]"
### Example
EXAMPLE="'https://www.youtube.com/watch?v=JoSY6AWKqHs' 00:01:59 2"

### Args
URL=$1
START=$2
DURATION=$3

### Check args exist
chkarg "$URL" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"
chkarg "$START" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"
chkarg "$DURATION" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"

### Check cmd exist
chkcmd "yt-dlp"
chkcmd "ffmpeg"

### quality
QUALITY=85
### fps
FPS=12
### width
WIDTH=480
### Output file
OUTPUT_FILE="$(date +"%Y%m%d%H%M%S").gif"

STREAM_URL=$(yt-dlp -g -f "bestvideo[height<=480]" -S "vcodec:h264" "$URL" 2>/dev/null)

ffmpeg -y -hide_banner \
  -loglevel error \
  -ss "$START" \
  -i "$STREAM_URL" \
  -t "$DURATION" \
  -vf "fps=$FPS,scale=$WIDTH:-1:flags=lanczos" \
  -f yuv4mpegpipe - |
  gifski -q \
    -Q "$QUALITY" \
    -o "$OUTPUT_FILE" -

printf "%s " "$OUTPUT_FILE"
ls -lh "$OUTPUT_FILE" | awk -F " " {'print $5'}
