#! /usr/bin/env bash
set -o errexit
set -o pipefail

### cmd
CMD=$(basename "$0")
### Description
DESC="Youtube Gif Maker (12fps)"
### Usage
USAGE="[video_link] [from(hh:mm:ss or sec)] [during(sec)]"
### Example
EXAMPLE="'https://www.youtube.com/watch?v=JoSY6AWKqHs' 00:01:59 2"

### Args
URL=$1
START=$2
DURATION=$3

### Check args exist
chkarg "$URL" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"
chkarg "$START" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"
chkarg "$DURATION" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"

### Check cmd exist
chkcmd "mkgif"
chkcmd "yt-dlp"

### Temp File
TMPFILE="$(mktemp -t "$(basename $0)")"

yt-dlp "$URL" \
  --quiet \
  -f 134 \
  --downloader \
  ffmpeg \
  --downloader-args \
  "ffmpeg_i:-ss $START -t $DURATION" \
  --force-overwrites \
  -o \
  "$TMPFILE"

mkgif "$TMPFILE" 00:00:00 "$DURATION"
rm -f "$TMPFILE"
