#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Description: Youtube Gif Maker (24fps)
# Usage: ytgifv [video_id] [from(hh:mm:ss or sec)] [during(sec)]
# Example: ytgifv JoSY6AWKqHs 00:01:59 2

### Args
URL=${1:-}
START=${2:-}
DURATION=${3:-}

# Check arguments
if [ -z "$DURATION" ]; then
  printf "\033[1mytgifv\033[0m: Youtube Gif Maker (24fps)\n" >&2
  printf "Usage: \033[1mytgifv\033[0m [video_id] [from(hh:mm:ss or sec)] [during(sec)]\n" >&2
  printf "       \033[1mytgifv\033[0m JoSY6AWKqHs 00:01:59 2\n" >&2
  exit 1
fi

# Check commands
command -v yt-dlp &>/dev/null || {
  echo "yt-dlp is not installed" >&2
  exit 1
}
command -v ffmpeg &>/dev/null || {
  echo "ffmpeg is not installed" >&2
  exit 1
}

### quality
QUALITY=85
### fps
FPS=24
### width
WIDTH=480
### Output file
OUTPUT_FILE="$(date +"%Y%m%d%H%M%S")_v.gif"

STREAM_URL=$(yt-dlp -g -f "bestvideo[height<=480]" -S "vcodec:h264" "$URL" 2>/dev/null)

ffmpeg -y -hide_banner \
  -loglevel error \
  -ss "$START" \
  -i "$STREAM_URL" \
  -t "$DURATION" \
  -vf "fps=$FPS,scale=$WIDTH:-1:flags=lanczos" \
  -f yuv4mpegpipe - |
  gifski -q \
    -Q "$QUALITY" \
    -o "$OUTPUT_FILE" -

printf "%s " "$OUTPUT_FILE"
ls -lh "$OUTPUT_FILE" | awk -F " " {'print $5'}
