#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Description: Youtube Music Downloader Full (With Metadata)
# Usage: ytmusfull [song_id]
# Example: ytmusfull dSeW7qZuMl0

### Args
URL=${1:-}

# Check arguments
if [[ -z "$URL" ]]; then
  printf "\033[1mytmusfull\033[0m: Youtube Music Downloader Full (With Metadata)\n" >&2
  printf "Usage: \033[1mytmusfull\033[0m [song_id]\n" >&2
  printf "       \033[1mytmusfull\033[0m dSeW7qZuMl0\n" >&2
  exit 1
fi

# Check commands
command -v yt-dlp &>/dev/null || {
  echo "yt-dlp is not installed" >&2
  exit 1
}

yt-dlp \
  --no-warnings \
  --progress \
  -f "141/140/bestaudio[ext=m4a]" \
  --extract-audio \
  --audio-format m4a \
  --embed-thumbnail \
  --convert-thumbnails jpg \
  --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v mjpeg -vf crop='min(iw,ih)':'min(iw,ih)'" \
  --embed-metadata \
  --parse-metadata 'playlist_index:%(meta_track)s' \
  --print before_dl:"[download] %(title)s.%(ext)s" \
  -o "%(title)s.%(ext)s" \
  --cookies-from-browser edge \
  "$URL"
