#! /usr/bin/env bash
set -o errexit
set -o pipefail

### cmd
CMD=$(basename "$0")
### Description
DESC="Youtube Music Downloader (Without Metadata)"
### Usage
USAGE="[song_url]"
### Example
EXAMPLE="'https://music.youtube.com/watch?v=dSeW7qZuMl0&si=ek3ENxoDCbS43QeS'"

### Args
URL=$1

### Check args exist
chkarg "$URL" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"

### Check cmd exist
chkcmd "yt-dlp"

yt-dlp \
  --no-warnings \
  --progress \
  -f 141 \
  --extract-audio \
  --embed-metadata \
  --parse-metadata "title:%(meta_title)s" \
  --parse-metadata ":(?P<meta_date>)" \
  --parse-metadata ":(?P<meta_description>)" \
  --parse-metadata ":(?P<meta_synopsis>)" \
  --parse-metadata ":(?P<meta_purl>)" \
  --parse-metadata ":(?P<meta_comment>)" \
  --parse-metadata ":(?P<meta_track>)" \
  --parse-metadata ":(?P<meta_artist>)" \
  --parse-metadata ":(?P<meta_genre>)" \
  --parse-metadata ":(?P<meta_album>)" \
  --parse-metadata ":(?P<meta_album_artist>)" \
  --parse-metadata ":(?P<meta_disc>)" \
  --parse-metadata ":(?P<meta_show>)" \
  --parse-metadata ":(?P<meta_season_number>)" \
  --parse-metadata ":(?P<meta_episode_id>)" \
  --parse-metadata ":(?P<meta_episode_sort>)" \
  --parse-metadata ":(?P<meta_language>)" \
  --print before_dl:"[download] %(title)s.%(ext)s" \
  -o "%(title)s.%(ext)s" \
  --cookies-from-browser chrome \
  "$URL"
