#! /usr/bin/env bash
set -o errexit
set -o pipefail

### cmd
CMD=$(basename "$0")
### Description
DESC="Youtube Music Downloader Full (With Metadata)"
### Usage
USAGE="[song_url]"
### Example
EXAMPLE="'https://music.youtube.com/watch?v=dSeW7qZuMl0&si=ek3ENxoDCbS43QeS'"

### Args
URL=$1

### Check args exist
chkarg "$URL" "$CMD" "$DESC" "$USAGE" "$EXAMPLE"

### Check cmd exist
chkcmd "yt-dlp"

yt-dlp \
  --no-warnings \
  --progress \
  -f "141/140/bestaudio[ext=m4a]" \
  --extract-audio \
  --audio-format m4a \
  --embed-thumbnail \
  --convert-thumbnails jpg \
  --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v mjpeg -vf crop='min(iw,ih)':'min(iw,ih)'" \
  --embed-metadata \
  --parse-metadata 'playlist_index:%(meta_track)s' \
  --print before_dl:"[download] %(title)s.%(ext)s" \
  -o "%(title)s.%(ext)s" \
  --cookies-from-browser edge \
  "$URL"
