#! /usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Description: Youtube Music Downloader (Without Metadata)
# Usage: ytmus [song_id]
# Example: ytmus dSeW7qZuMl0


### Args
URL=${1:-}

# Check arguments
if [ -z "$URL" ]; then
  printf "\033[1mytmus\033[0m: Youtube Music Downloader (Without Metadata)\n" >&2
  printf "Usage: \033[1mytmus\033[0m [song_id]\n" >&2
  printf "       \033[1mytmus\033[0m dSeW7qZuMl0\n" >&2
  exit 1
fi

# Check commands
command -v yt-dlp &> /dev/null || { echo "yt-dlp is not installed" >&2; exit 1; }

yt-dlp \
  --no-warnings \
  --progress \
  -f "141/140/bestaudio[ext=m4a]" \
  --extract-audio \
  --audio-format m4a \
  --postprocessor-args "ffmpeg:-map_metadata -1 -metadata title=\"%(title)s\"" \
  --print before_dl:"[download] %(title)s.%(ext)s" \
  -o "%(title)s.%(ext)s" \
  --cookies-from-browser edge \
  "$URL"
