from datetime import datetime

file_list = [
    '/Users/florencea/GitHub/my-macos-build/configs/element-custom-rules-desktop.txt',
    '/Users/florencea/GitHub/my-macos-build/configs/element-custom-rules-mobile.txt'
]


def combine_rules(file_name):
    with open(file_name, 'r') as rule_file:
        repeat_flag = True
        repeat_temp_key = ''
        input_list = []
        for line in rule_file:
            if line != '\n':
                input_list.append(line)
        list.sort(input_list)
        for line in input_list:
            if ':style(' in line:
                line_list = line.split(':style(')
                if line_list[0] in rule_dict:
                    rule_dict[line_list[0]].append(line_list[1].replace(')\n', ''))
                else:
                    rule_dict[line_list[0]] = [line_list[1].replace(')\n', '')]
                if repeat_temp_key != line_list[0]:
                    repeat_flag = False
                    output_line_key = repeat_temp_key
                    repeat_temp_key = line_list[0]
                else:
                    repeat_flag = True
                if repeat_flag is False and output_line_key != '':
                    list.sort(rule_dict[output_line_key])
                    output_line = output_line_key + ':style(' + '; '.join(rule_dict[output_line_key]) + ')'
                    output_data_list_style.append(output_line)
            else:
                if '! ' in line:
                    if 'Description:' in line or 'Last updated:' in line or 'Title:' in line:
                        if 'Title:' in line:
                            output_data_list_meta.append(line.strip() + ' minified')
                        else:
                            output_data_list_meta.append(line.strip())
                elif '||' in line:
                    output_data_list_host.append(line.strip())
                else:
                    output_data_list_remove.append(line.strip())


for file_name in file_list:
    output_data_list_meta = []
    output_data_list_remove = []
    output_data_list_host = []
    output_data_list_style = []
    rule_dict = {}
    combine_rules(file_name)
    list.sort(output_data_list_remove)
    list.sort(output_data_list_style)
    with open(file_name.split('.')[0] + '.combined.txt', 'w') as output_file:
        for line in output_data_list_meta:
            print(line, file=output_file)
        print('! generated by rule-combiner.py ' + datetime.now().isoformat(), file=output_file)
        print('! remove rules', file=output_file)
        for line in output_data_list_remove:
            print(line, file=output_file)
        print('! host rules', file=output_file)
        for line in output_data_list_host:
            print(line, file=output_file)
        print('! style rules', file=output_file)
        for line in output_data_list_style:
            print(line, file=output_file)
